<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MyEcore" nsURI="http://ntnu.no/krirek/ecore/test" nsPrefix="no.ntnu">
  <eClassifiers xsi:type="ecore:EClass" name="TestClass">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the main class. Kristian is cool &#xD;&#xA;"/>
    </eAnnotations>
    <eOperations name="myOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MyAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MyReference" eType="#//TestClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="me" lowerBound="1" eType="#//TestClass"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meToo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Very cool!"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MyEnum" instanceTypeName="MyEnumType"/>
  <eClassifiers xsi:type="ecore:EDataType" name="MyData" instanceTypeName="EString"/>
  <eClassifiers xsi:type="ecore:EClass" name="Circular"/>
</ecore:EPackage>
